### ISSUE TITLE
config questions

### ISSUE THREAD

**Issue by borgauf** [flexibeast/plisp-mode#3]
I've seen [https://github.com/tj64/picolisp-mode](url) and it gives config info. How much of that should I use with your version of picolisp-mode? BTW, I'm trying to run picoLisp in org-mode and I get a 

```
executing Picolisp source code block
org-babel-picolisp-initiate-session: Cannot open load file: No such file or directory, inferior-picolisp
```
inferior-picolisp being set/known is the "run-picolisp" if I'm not mistaken. . . .

**Comment by flexibeast** [comment]
Firstly, some relevant background info:

* [A GitHub thread in which i go into details about the various picolisp-modes](https://github.com/melpa/melpa/issues/2514)

* [A thread on the PicoLisp mailing list from earlier this year, in which the various picolisp-modes are discussed](https://www.mail-archive.com/picolisp@software-lab.de/msg08519.html)

If you're installing my `picolisp-mode` package from MELPA, the main two areas of configuration you might need to consider are:

* setting the `picolisp-pil-executable`,  `picolisp-pilindent-executable`, and `picolisp-documentation-directory` variables, depending on how your PicoLisp installation is set up; their default values might "just work".

* automatically enabling my `picolisp-mode` when you open a `.l` file will indeed require you to do:
    (add-to-list 'auto-mode-alist '("\\.l$" . picolisp-mode))

i'm not aware of any conflict(s) between my mode and `paredit-mode`, which i don't use myself; please let me know if you find one or much such conflicts.

`tsm-mode` is not something my mode needs or uses; it's actually part of the other `picolisp-mode` packages.

Finally, it looks like the `org-babel` support for PicoLisp assumes the specific implementations provided by the other `picolisp-mode` packages - my package doesn't include a `run-picolisp` function, for example, as that function name isn't namespace-clean. So if you're wanting to use PicoLisp in `org-babel` contexts, in the immediate future you'll need to use one of the other `picolisp-mode` packages.

**Comment by cryptorick** [comment]
Hey Lawrence (@borgauf)!

You'll have to do some extra work (not too much though) to get Org Babel sessions to work with @flexibeast's repo here.  Read all about it how to do that here: https://github.com/cryptorick/standalone-inferior-picolisp.

Best, Rick

**Comment by flexibeast** [comment]
As Org Babel session support is now provided (details [here](https://github.com/flexibeast/plisp-mode#usage-org-babel)), i'm closing this issue.
